package com.asjy.commerplat.model;

import java.util.Date;

public class Ad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.titlename
     *
     * @mbggenerated
     */
    private String titlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.display
     *
     * @mbggenerated
     */
    private Boolean display;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ad.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.id
     *
     * @return the value of tb_ad.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.id
     *
     * @param id the value for tb_ad.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.addtime
     *
     * @return the value of tb_ad.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.addtime
     *
     * @param addtime the value for tb_ad.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.titlename
     *
     * @return the value of tb_ad.titlename
     *
     * @mbggenerated
     */
    public String getTitlename() {
        return titlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.titlename
     *
     * @param titlename the value for tb_ad.titlename
     *
     * @mbggenerated
     */
    public void setTitlename(String titlename) {
        this.titlename = titlename == null ? null : titlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.path
     *
     * @return the value of tb_ad.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.path
     *
     * @param path the value for tb_ad.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.seq
     *
     * @return the value of tb_ad.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.seq
     *
     * @param seq the value for tb_ad.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.display
     *
     * @return the value of tb_ad.display
     *
     * @mbggenerated
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.display
     *
     * @param display the value for tb_ad.display
     *
     * @mbggenerated
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ad.url
     *
     * @return the value of tb_ad.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ad.url
     *
     * @param url the value for tb_ad.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}