package com.asjy.commerplat.model;

public class FloorGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_floor_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_floor_goods.floorid
     *
     * @mbggenerated
     */
    private Integer floorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_floor_goods.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_floor_goods.id
     *
     * @return the value of tb_floor_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_floor_goods.id
     *
     * @param id the value for tb_floor_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_floor_goods.floorid
     *
     * @return the value of tb_floor_goods.floorid
     *
     * @mbggenerated
     */
    public Integer getFloorid() {
        return floorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_floor_goods.floorid
     *
     * @param floorid the value for tb_floor_goods.floorid
     *
     * @mbggenerated
     */
    public void setFloorid(Integer floorid) {
        this.floorid = floorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_floor_goods.goodsid
     *
     * @return the value of tb_floor_goods.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_floor_goods.goodsid
     *
     * @param goodsid the value for tb_floor_goods.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}