package com.asjy.commerplat.model;

public class FloorClasses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_floor_classes.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_floor_classes.floorid
     *
     * @mbggenerated
     */
    private Integer floorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_floor_classes.classesid
     *
     * @mbggenerated
     */
    private Integer classesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_floor_classes.id
     *
     * @return the value of tb_floor_classes.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_floor_classes.id
     *
     * @param id the value for tb_floor_classes.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_floor_classes.floorid
     *
     * @return the value of tb_floor_classes.floorid
     *
     * @mbggenerated
     */
    public Integer getFloorid() {
        return floorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_floor_classes.floorid
     *
     * @param floorid the value for tb_floor_classes.floorid
     *
     * @mbggenerated
     */
    public void setFloorid(Integer floorid) {
        this.floorid = floorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_floor_classes.classesid
     *
     * @return the value of tb_floor_classes.classesid
     *
     * @mbggenerated
     */
    public Integer getClassesid() {
        return classesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_floor_classes.classesid
     *
     * @param classesid the value for tb_floor_classes.classesid
     *
     * @mbggenerated
     */
    public void setClassesid(Integer classesid) {
        this.classesid = classesid;
    }
}