package com.asjy.commerplat.model;

public class GoodsSpec {

    private Integer id;
    private Integer goodsid;
    private Integer specid;
    private Integer specvid;
	private String goodsnumber;
    private Goods goods;
    
    
    public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spec.id
     *
     * @param id the value for tb_goods_spec.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spec.goodsid
     *
     * @return the value of tb_goods_spec.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spec.goodsid
     *
     * @param goodsid the value for tb_goods_spec.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spec.specid
     *
     * @return the value of tb_goods_spec.specid
     *
     * @mbggenerated
     */
    public Integer getSpecid() {
        return specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spec.specid
     *
     * @param specid the value for tb_goods_spec.specid
     *
     * @mbggenerated
     */
    public void setSpecid(Integer specid) {
        this.specid = specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spec.specvid
     *
     * @return the value of tb_goods_spec.specvid
     *
     * @mbggenerated
     */
    public Integer getSpecvid() {
        return specvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spec.specvid
     *
     * @param specvid the value for tb_goods_spec.specvid
     *
     * @mbggenerated
     */
    public void setSpecvid(Integer specvid) {
        this.specvid = specvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spec.goodsnumber
     *
     * @return the value of tb_goods_spec.goodsnumber
     *
     * @mbggenerated
     */
    public String getGoodsnumber() {
        return goodsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spec.goodsnumber
     *
     * @param goodsnumber the value for tb_goods_spec.goodsnumber
     *
     * @mbggenerated
     */
    public void setGoodsnumber(String goodsnumber) {
        this.goodsnumber = goodsnumber == null ? null : goodsnumber.trim();
    }
}