package com.asjy.commerplat.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order {


    private Integer id;
    private Date addtime;
    private Integer userid;
    private String ordernumber;
    private String cityaddress;
    private String detailaddress;
    private String receiver;
    private String tel;
    private String zipcode;
    private String orderstate;
    private BigDecimal totalprice;
    private List<Detailorder> list_detailorder;
    private User user;

    public List<Detailorder> getList_detailorder() {
		return list_detailorder;
	}

	public void setList_detailorder(List<Detailorder> list_detailorder) {
		this.list_detailorder = list_detailorder;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.addtime
     *
     * @return the value of tb_order.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.addtime
     *
     * @param addtime the value for tb_order.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.userid
     *
     * @return the value of tb_order.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.userid
     *
     * @param userid the value for tb_order.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.ordernumber
     *
     * @return the value of tb_order.ordernumber
     *
     * @mbggenerated
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.ordernumber
     *
     * @param ordernumber the value for tb_order.ordernumber
     *
     * @mbggenerated
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.cityaddress
     *
     * @return the value of tb_order.cityaddress
     *
     * @mbggenerated
     */
    public String getCityaddress() {
        return cityaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.cityaddress
     *
     * @param cityaddress the value for tb_order.cityaddress
     *
     * @mbggenerated
     */
    public void setCityaddress(String cityaddress) {
        this.cityaddress = cityaddress == null ? null : cityaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.detailaddress
     *
     * @return the value of tb_order.detailaddress
     *
     * @mbggenerated
     */
    public String getDetailaddress() {
        return detailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.detailaddress
     *
     * @param detailaddress the value for tb_order.detailaddress
     *
     * @mbggenerated
     */
    public void setDetailaddress(String detailaddress) {
        this.detailaddress = detailaddress == null ? null : detailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver
     *
     * @return the value of tb_order.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver
     *
     * @param receiver the value for tb_order.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.tel
     *
     * @return the value of tb_order.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.tel
     *
     * @param tel the value for tb_order.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.zipcode
     *
     * @return the value of tb_order.zipcode
     *
     * @mbggenerated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.zipcode
     *
     * @param zipcode the value for tb_order.zipcode
     *
     * @mbggenerated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderstate
     *
     * @return the value of tb_order.orderstate
     *
     * @mbggenerated
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderstate
     *
     * @param orderstate the value for tb_order.orderstate
     *
     * @mbggenerated
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate == null ? null : orderstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.totalprice
     *
     * @return the value of tb_order.totalprice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.totalprice
     *
     * @param totalprice the value for tb_order.totalprice
     *
     * @mbggenerated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }
}