package com.asjy.commerplat.model;

import java.util.Date;
import java.util.List;

public class Spec {
    
    private Integer id;

    private Date addtime;

    private String specname;

    private Integer seq;
    private Integer specvid;
    private String specvname;
    public Integer getSpecvid() {
		return specvid;
	}

	public void setSpecvid(Integer specvid) {
		this.specvid = specvid;
	}

	public String getSpecvname() {
		return specvname;
	}

	public void setSpecvname(String specvname) {
		this.specvname = specvname;
	}

	private String specvnames;
    
    private List<Specv> list_specv;

    public List<Specv> getList_specv() {
		return list_specv;
	}

	public void setList_specv(List<Specv> list_specv) {
		this.list_specv = list_specv;
	}

	public String getSpecvnames() {
		return specvnames;
	}

	public void setSpecvnames(String specvnames) {
		this.specvnames = specvnames;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spec.id
     *
     * @return the value of tb_spec.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spec.id
     *
     * @param id the value for tb_spec.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spec.addtime
     *
     * @return the value of tb_spec.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spec.addtime
     *
     * @param addtime the value for tb_spec.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spec.specname
     *
     * @return the value of tb_spec.specname
     *
     * @mbggenerated
     */
    public String getSpecname() {
        return specname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spec.specname
     *
     * @param specname the value for tb_spec.specname
     *
     * @mbggenerated
     */
    public void setSpecname(String specname) {
        this.specname = specname == null ? null : specname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spec.seq
     *
     * @return the value of tb_spec.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spec.seq
     *
     * @param seq the value for tb_spec.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
}