package com.asjy.commerplat.model;

import java.util.Date;

public class Specv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specv.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specv.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specv.specname
     *
     * @mbggenerated
     */
    private String specvname;

    public String getSpecvname() {
		return specvname;
	}

	public void setSpecvname(String specvname) {
		this.specvname = specvname;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specv.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specv.specid
     *
     * @mbggenerated
     */
    private Integer specid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specv.id
     *
     * @return the value of tb_specv.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specv.id
     *
     * @param id the value for tb_specv.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specv.addtime
     *
     * @return the value of tb_specv.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specv.addtime
     *
     * @param addtime the value for tb_specv.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specv.seq
     *
     * @return the value of tb_specv.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specv.seq
     *
     * @param seq the value for tb_specv.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specv.specid
     *
     * @return the value of tb_specv.specid
     *
     * @mbggenerated
     */
    public Integer getSpecid() {
        return specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specv.specid
     *
     * @param specid the value for tb_specv.specid
     *
     * @mbggenerated
     */
    public void setSpecid(Integer specid) {
        this.specid = specid;
    }
}