package com.asjy.commerplat.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.asjy.commerplat.model.Ad;

@Mapper
public interface AdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad
     *
     * @mbggenerated
     */
    int insert(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad
     *
     * @mbggenerated
     */
    int insertSelective(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad
     *
     * @mbggenerated
     */
    Ad selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ad record);

	List<Ad> findAll();

	List<Ad> findRandomFiveAd();
}