package com.asjy.commerplat.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.asjy.commerplat.model.Classes;



@Mapper
public interface ClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classes
     *
     * @mbggenerated
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classes
     *
     * @mbggenerated
     */
    int insertSelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classes
     *
     * @mbggenerated
     */
    Classes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Classes record);
    
    
	List<Classes> findbypid(Integer pid);

	
	List<Classes> selectByPid(Integer pid);

	
	Classes findById(Integer id);

	
	List<Classes> findToGrandSon();

	
	List<Classes> find2sonbypid(Integer pid);
	

	
}