package com.asjy.commerplat.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.asjy.commerplat.model.Detailorder;

@Mapper
public interface DetailorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detailorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detailorder
     *
     * @mbggenerated
     */
    int insert(Detailorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detailorder
     *
     * @mbggenerated
     */
    int insertSelective(Detailorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detailorder
     *
     * @mbggenerated
     */
    Detailorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detailorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Detailorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detailorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Detailorder record);

	int deleteByOrderId(Integer orderid);

	List<Detailorder> findByOrderid(Integer orderid);

	List<Detailorder> findByGoodsId(Integer id);
}