package com.asjy.commerplat.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.asjy.commerplat.model.FloorGoods;

@Mapper
public interface FloorGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor_goods
     *
     * @mbggenerated
     */
    int insert(FloorGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor_goods
     *
     * @mbggenerated
     */
    int insertSelective(FloorGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor_goods
     *
     * @mbggenerated
     */
    FloorGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FloorGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FloorGoods record);

	int deleteByFloord(Integer id);

	int ajaxdeleteByFloorids(List<Integer> ids);

	int insertArrGoods(@Param("arr")Integer[] arr, @Param("id")Integer id);

	List<FloorGoods> findByGoodsId(Integer id);
}