package com.asjy.commerplat.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.asjy.commerplat.model.Floor;

@Mapper
public interface FloorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor
     *
     * @mbggenerated
     */
    int insert(Floor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor
     *
     * @mbggenerated
     */
    int insertSelective(Floor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor
     *
     * @mbggenerated
     */
    Floor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Floor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_floor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Floor record);

	

	List<Floor> findByPid(Integer pid);

	int ajaxdeleteids(List<Integer> ids);

	Floor FloorSelectById(Integer id);

	List<Floor> FloorSelectAll();
	
	List<Floor> FloorSelectByDisplay();
}