package com.asjy.commerplat.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.asjy.commerplat.model.GoodsSpec;

@Mapper
public interface GoodsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_spec
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_spec
     *
     * @mbggenerated
     */
    int insert(GoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_spec
     *
     * @mbggenerated
     */
    int insertSelective(GoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_spec
     *
     * @mbggenerated
     */
    GoodsSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsSpec record);

    GoodsSpec findByGoodsnumberAndSpecvid(@Param("specvid1")Integer specvid1, @Param("specvid2")Integer specvid2, @Param("goodsnumber")String goodsnumber);

	List<GoodsSpec> findByGoodsId(Integer goodsid);
	
	List<GoodsSpec> findBySpecId(Integer specvid);

	int deleteByGoodsId(Integer goodsid);
}