package com.asjy.commerplat.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.asjy.commerplat.model.Goods;

@Mapper
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Goods record);

	List<Goods> findAll();

	Goods findByGoodsNumber(String goodsnumber);

	List<Goods> findByRecommend(int i);

	List<Goods> selectGoodsByClassidAndGoodsname(@Param("goodsname")String goodsname, @Param("list_classesid")List<Integer> list_classesid);

	List<Goods> findByConditions(@Param("list_classesid")List<Integer> list_classesid, @Param("goodsname")String goodsname, @Param("currentPage")Integer currentPage, @Param("orderBy")String orderBy,
			@Param("orderType")String orderType, @Param("area_id")Integer area_id, @Param("gs_ids")Integer gs_ids, @Param("brand_ids")Integer brand_ids, @Param("properties")String properties, @Param("keyword")String keyword,
			@Param("all_property_status")String all_property_status, @Param("detail_property_status")String detail_property_status, @Param("priceEnd")BigDecimal priceEnd,@Param("priceBegin")BigDecimal priceBegin);

	List<Goods> findByNewGoods();

	List<Goods> findByinventoryGoods();

	List<GoodsMapper> findByClasses(Integer classid);

	List<GoodsMapper> findByBrand(Integer brandid);

}