package com.asjy.commerplat.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.asjy.commerplat.model.GoodsImages;


@Mapper
public interface GoodsImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_images
     *
     * @mbggenerated
     */
    int insert(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_images
     *
     * @mbggenerated
     */
    int insertSelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_images
     *
     * @mbggenerated
     */
    GoodsImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsImages record);

	List<GoodsImages> findByGoodsId(Integer goodsid);

	GoodsImages findBYId(Integer id);
}