package com.asjy.commerplat.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.asjy.commerplat.model.Order;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

	Order selectByOrdernumber(String ordernumber);

	List<Order> selectByUserid(@Param("userid")Integer userid, @Param("ordernumber")String ordernumber, @Param("begintime")String begintime, @Param("endtime")String endtime, @Param("orderstate")String orderstate);

	int deleteHavePayOrderById(Integer id);

	List<Order> findAll();

	Boolean deleteOrderById_back(Integer deleteid);
	
	Order selectByPrimaryKey_back(Integer id);

	Map<String, Object> getMonth();

	List<Order> findByconditions_back(@Param("ordernumber")String ordernumber, @Param("begintime")String begintime, @Param("endtime")String endtime, @Param("orderstate")String orderstate);


	
	
	
	
}