package com.asjy.commerplat.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.asjy.commerplat.model.Spec;
@Mapper
public interface SpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int insert(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int insertSelective(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    Spec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Spec record);

	List<Spec> findAll();

	List<Spec> findByGoodsNumber(String goodsnumber);

	List<Spec> findByGoodsId(Integer id);

	Map<String, Object> findByGoodsnumberAndSpecvid(Integer specvid1, Integer specvid2, String goodsnumber);

	Spec selectedById(Integer id);
}